# Generated by Django 3.1.4 on 2022-07-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220704_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='date_dy',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entries',
            name='date_yr',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
